name: Release mcworld

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Build mcworld
        run: python main.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: '*.mcworld'
